import 'package:dartz/dartz.dart';
import 'package:voclio_app/core/errors/failures.dart';

class SummarizeNoteUseCase {
  // TODO: Inject NoteRepository when available

  Future<Either<Failure, String>> call(String noteId) async {
    try {
      // TODO: Call repository method
      // This will integrate with Gemini API
      await Future.delayed(const Duration(seconds: 2));
      return const Right('This is a summary generated by Gemini AI...');
    } catch (e) {
      return Left(ServerFailure());
    }
  }
}

class ExtractTasksFromNoteUseCase {
  // TODO: Inject NoteRepository when available

  Future<Either<Failure, List<String>>> call(String noteId) async {
    try {
      // TODO: Call repository method
      // This will integrate with Gemini API to extract actionable tasks
      await Future.delayed(const Duration(seconds: 2));
      return const Right([
        'Complete project report',
        'Schedule meeting with team',
        'Review documentation',
      ]);
    } catch (e) {
      return Left(ServerFailure());
    }
  }
}
